// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXNkBZ_EwYJdpZxYV9nCd0YtN7Oi6N6eo',
    appId: '1:264478702980:web:f89cf2d24efe827d0071d1',
    messagingSenderId: '264478702980',
    projectId: 'startenic-49e30',
    authDomain: 'startenic-49e30.firebaseapp.com',
    storageBucket: 'startenic-49e30.appspot.com',
    measurementId: 'G-WK4HWJ2WPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1il_qxvvNNOnyYV6O2BY7zAcjUALyNao',
    appId: '1:264478702980:android:0720aae52ba096aa0071d1',
    messagingSenderId: '264478702980',
    projectId: 'startenic-49e30',
    storageBucket: 'startenic-49e30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdzHFAYnqaJvFrdr6KrtbBP9DkVPqeQPU',
    appId: '1:264478702980:ios:90052f2475a697dd0071d1',
    messagingSenderId: '264478702980',
    projectId: 'startenic-49e30',
    storageBucket: 'startenic-49e30.appspot.com',
    iosBundleId: 'com.example.startenic1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdzHFAYnqaJvFrdr6KrtbBP9DkVPqeQPU',
    appId: '1:264478702980:ios:90052f2475a697dd0071d1',
    messagingSenderId: '264478702980',
    projectId: 'startenic-49e30',
    storageBucket: 'startenic-49e30.appspot.com',
    iosBundleId: 'com.example.startenic1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXNkBZ_EwYJdpZxYV9nCd0YtN7Oi6N6eo',
    appId: '1:264478702980:web:307f09b5035b9a360071d1',
    messagingSenderId: '264478702980',
    projectId: 'startenic-49e30',
    authDomain: 'startenic-49e30.firebaseapp.com',
    storageBucket: 'startenic-49e30.appspot.com',
    measurementId: 'G-RY84G32KQE',
  );
}
